Bump aquarius version
oceanprotocol/market pull request #837
Opened 2021-09-03 12:18 UTC by mihaisc

The new version of aqua (not sure what version it will be) changes a few things in the endpoint structure and request/response.

The procedure is

- [ ] test and approve pr
- [ ] swap aquarius with aquarius 2
- [ ] merge pr

2021-09-13 10:40 UTC, kremalicious requested changes

2021-09-13 10:40 UTC, kremalicious commented on src/components/templates/Search/index.tsx
> +    const source = axios.CancelToken.source()
We have to use the cancel token within this `useEffect`, in its`return` callback so that unmounting it really cancels the request

2021-09-13 10:40 UTC, kremalicious commented on src/components/templates/Search/index.tsx
>      if (!appConfig.metadataCacheUri) return
If we don't pass `appConfig.metadataCacheUri` anymore we also don't need to check for it up here

2021-09-13 10:48 UTC, kremalicious commented
Functionality-wise all seems to work well, I could not break it and results indeed seem more relevant. 

As side note regarding #769, result is now on 2nd place so improvement from before
https://market-git-feature-bump-aquarius-oceanprotocol.vercel.app/search?sort=_score&sortOrder=desc&text=RUMNAR-48

And indeed lots of breaking changes for end users of our remote Aquarius. Gonna have a hard time explaining why a simple patch release breaks all existing search implementations

2021-09-13 11:34 UTC, mihaisc commented
Regarding #769 i did some quick tests and it's more complicated that i thought, we need to rethink a bit the query and maybe the types in es.

2021-09-13 12:46 UTC, kremalicious approved these changes

2021-09-15 06:43 UTC, bogdanfazakas approved these changes
works good on my side, there is a conflict after the latest merges into main that needs some attention

2021-09-24 09:38 UTC, merged